name: actions

on:
  push:

jobs:
  test-actions:
    name: test-action
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls
      - name: checkout 
        uses: actions/checkout@v4
      - name: ls
        run: ls
      - name: hello-world-action
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "nader"
      - name: time
        run: echo "'greeting time:' ${{ steps.hello-world-action.outputs.time }}"
      - name: docker action
        uses: docker://hello-world:latest
      
       
  
